package com.example.ticket.enums;

public enum EventStatus {
    DRAFT, SUBMITTED, ADMIN_REVIEWING, MATCHING,
    PENDING_VENUE_APPROVAL, VENUE_ACCEPTED, VENUE_REJECTED,
    CONTRACT_CONFIRMED, PUBLISHED, ONGOING, COMPLETED, SETTLED, CANCELLED
}
