spring:
  application:
    name: ticket
  datasource:
    url: "jdbc:mysql://localhost:3306/booking_ticket"
    username: root
    password: 271204
  data:
    mongodb:
      uri: mongodb://localhost:27017/datn
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyenthanhbinh271204@gmail.com
    password: yemjqppmqyixivba
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

server:
  port: 8080
  servlet:
    context-path: /ticket

jwt:
  secretKey: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9
  valid-duration: 15   # phut
  refresh-duration: 3    #ngay

mail:
  host: smtp.gmail.com
  port: 587
  username: nguyenthanhbinh271204@gmail.com
  password: yemjqppmqyixivba
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true


cloudinary:
  cloud_name: ddoffadkr
  api_key: 489282433767684
  api_secret: yrBWIY_98-iFnDjFe86PeDGBABw


momo:
  partner-code: MOMO
  access-key: F8BBA842ECF85500
  secret-key: K951B6PE1waDMi640xX08PD3vg6EkVlz
  endpoint: https://test-payment.momo.vn/v2/gateway/api/create
  redirect-url: http://localhost:8080/ticket/payments/momo/return
  ipn-url: http://localhost:8080/ticket/payments/momo/ipn